### Main settings ###
title: Bitrix Kit
lang: ru
# URL
permalink: pretty

### Theme ###
remote_theme: pmarsceill/just-the-docs

# "light" (default) and "dark"
color_scheme: light

aux_links:
  "Česnakas on GitHub":
    - "//github.com/cesnakas"

aux_links_new_tab: true

gh_edit_link: false

search_enabled: false
