### Main settings ###
title: Bitrix Kit
lang: ru
# URL
permalink: pretty

### Theme ###
remote_theme: pmarsceill/just-the-docs

# "light" (default) and "dark"
color_scheme: bitrix

aux_links:
  "Česnakas on GitHub":
    - "//github.com/cesnakas"

aux_links_new_tab: true

gh_edit_link: false

search_enabled: true
search:
  preview_words_before: 3
  preview_words_after: 3
  lang:
    - en
    - ru

# footer_content: Copyright &copy; 2022

plugins:
  - jekyll-seo-tag
  - search:
      lang:
        - en
        - ru

# Styles
sass:
  style: :compressed
